FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /data /var/lib/rustqueue && chown -R 65532:65532 /data /var/lib/rustqueue
COPY .docker-bin/rustqueued /usr/local/bin/rustqueued
COPY .docker-bin/rustqueue-discovery /usr/local/bin/rustqueue-discovery
COPY .docker-bin/rustqueue-proxy /usr/local/bin/rustqueue-proxy
COPY .docker-bin/rustqueue-bench /usr/local/bin/rustqueue-bench
COPY .docker-bin/rustqueuectl /usr/local/bin/rustqueuectl
COPY .docker-bin/rustqueue-console /usr/local/bin/rustqueue-console
COPY console-ui/dist /usr/share/rustqueue-console
USER 65532:65532
WORKDIR /var/lib/rustqueue
EXPOSE 4150 4151 4161 4180
ENTRYPOINT ["/usr/local/bin/rustqueued"]
