[package]
name = "rustqueue-queue"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
crash-injection = ["rustqueue-storage/crash-injection"]

[dependencies]
anyhow.workspace = true
bytes.workspace = true
crc32c.workspace = true
futures.workspace = true
hex.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
rustqueue-storage = { path = "../storage" }
rustqueue-protocol = { path = "../protocol" }
rustqueue-telemetry.workspace = true

[dev-dependencies]
libc.workspace = true
tempfile.workspace = true
