apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rustqueue.operatorServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustqueue.labels" . | nindent 4 }}
