x-rustqueue: &rustqueue
  image: rustqueue:dev
  build:
    context: ..
  volumes:
    - ./dev-certs:/certs:ro
  environment:
    RUST_LOG: info,rustqueued::tcp=debug
  healthcheck:
    test: ["CMD", "curl", "-fsS", "http://127.0.0.1:4151/v1/health"]
    interval: 2s
    timeout: 1s
    retries: 30
  restart: unless-stopped

services:
  rustqueue-1:
    <<: *rustqueue
    command: ["--config", "/etc/rustqueue.toml"]
    hostname: rustqueue-1
    ports: ["4150:4150", "4151:4151"]
    volumes:
      - rustqueue-1:/data
      - ./dev-certs:/certs:ro
      - ./node-1.toml:/etc/rustqueue.toml:ro
  rustqueue-2:
    <<: *rustqueue
    command: ["--config", "/etc/rustqueue.toml"]
    hostname: rustqueue-2
    ports: ["5150:4150", "5151:4151"]
    volumes:
      - rustqueue-2:/data
      - ./dev-certs:/certs:ro
      - ./node-2.toml:/etc/rustqueue.toml:ro
  rustqueue-3:
    <<: *rustqueue
    command: ["--config", "/etc/rustqueue.toml"]
    hostname: rustqueue-3
    ports: ["6150:4150", "6151:4151"]
    volumes:
      - rustqueue-3:/data
      - ./dev-certs:/certs:ro
      - ./node-3.toml:/etc/rustqueue.toml:ro

volumes:
  rustqueue-1:
  rustqueue-2:
  rustqueue-3:
