[package]
name = "rustqueue-bench"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rustqueue-bench"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
hdrhistogram.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
