apiVersion: v2
name: rustqueue
description: RustQueue Broker cluster and Kubernetes Operator
type: application
version: 0.6.0
appVersion: "0.6.0"
kubeVersion: ">=1.28.0-0"
keywords:
  - messaging
  - nsq
  - raft
  - operator
