[package]
name = "rustqueue-discovery"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rustqueue-discovery"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
futures.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustqueue-telemetry.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tower.workspace = true
